GraspDetectorOPD:
  ros__parameters:
    #cloud_topic: /camera/pointcloud
    cloud_topic: /mechmind/color_point_cloud
    rviz: true
    device: 0 # 0:CPU, 1:GPU, 2:VPU
    auto_mode: true
    plane_remove: true
    # grasp workspace in camera frames
    #workspace: [-0.21, 0.29, -0.22, 0.15, 0.0, 1.0] # Realsense
    workspace: [-0.16, 0.28, -0.26, 0.14, 1.4, 1.65] # Mechmind
    # gripper geometry parameters in metre
    # finger_width: the finger thickness
    # hand_outer_diameter: the maximum robot hand aperture 
    # hand_depth: the hand depth (the finger length)
    # hand_height: the finger breadth
    finger_width: 0.005
    hand_outer_diameter: 0.100
    hand_depth: 0.038
    hand_height: 0.020
    num_samples: 200
GraspPlanner:
  ros__parameters:
    grasp_score_threshold: 0
    grasp_frame_id: "base"
    grasp_approach: [0.0, 0.0, -1.0]
    #grasp_approach_angle: 1.0 # 1.047=PI/3 # 0.785=PI/4 # 0.523=PI/6 # 0.345=PI/9 # acceptable approaching angle
    grasp_offset: [0.000, 0.000, 0.0]
    # grasp boundry in grasp_frame_id
    grasp_boundry: [-0.2, 0.2, -0.65, -0.30, -0.15, 0.15]
    eef_offset: 0.202
    eef_yaw_offset: 0.0 #-0.7854 # M_PI/4
    finger_joint_names: ["panda_finger_joint1", "panda_finger_joint2"]
