ur_test:
    ros__parameters:
        host: "192.168.0.5"
        shutdown_on_disconnect: true
        joint_names: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]